# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "client"

[jobs.client]
command = [
    "cargo", "run",
    "--color", "always",
]
need_stdout = true
allow_warnings = true
background = true
watch = [
    "src/ui/**/*.rs",
    "src/ui/**/*.ui",
    "src/ui/**/*.xml",
    "src/ui/**/*.css",
    "src/client.rs",
]

summary = true
on_change_strategy = "kill_then_restart"

[jobs.server]
command = [
    "cargo", "run",
    "--bin", "server",
    "--color", "always",
]
need_stdout = true
allow_warnings = true
background = true
watch = [
    "src/backend/**/*.rs",
    "src/server.rs",
    "Cargo.toml",
]
summary = true
on_change_strategy = "kill_then_restart"

